---
title: "人は直観的にベイズの定理を使っている？"
lang: ja
date: "2023-03-29"
draft: true
---

## ベイズの定理とは？

ベイズの定理は，統計学において最も有名な定理の一つですが，統計分析などを行ったことのない方々にとっては，あまり馴染みのないものかもしれません．

ベイズの定理は， @eq-bayes のように表すことができます．

$$
P(A|B) \propto P(B|A) P(A)
$$ {#eq-bayes}

@eq-bayes は，以下のことを示しています．

-   ある結果$B$が生じた場合に，それが原因$A$によるものである確率$P(A|B)$は
-   ある原因$A$の生じる確率$P(A)$とある原因$A$のもとで結果$B$が生じる確率$P(B|A)$の掛け算に比例（$\propto$）する

もっと身近なもので例えてみましょう． たとえば，

-   原因$A$：新型コロナへの感染の有無
-   結果$B$：PCR検査などでの診断結果

と考えれば， @eq-bayes を @eq-bayes-covid19 のように置き換えることができます．

$$
P(感染の有無|診断結果) \propto P(診断結果|感染の有無) P(感染の有無)
$$ {#eq-bayes-covid19}

以下では， @eq-bayes-covid19 に基づき，ベイズの定理の重要性について説明します．

### なぜベイズの定理が重要なのか？

@eq-bayes-covid19 に示したベイズの定理に出てくる3つの確率は，下の表のように，どれも非常に重要な指標と対応しています． そして， @eq-bayes-covid19 からは，検査の精度（感度・特異度）が高くても，検査前確率が低ければ陽性的中率が低くなることなどがわかるのです．

+--------------------------+-----------------------------------------------------------------+
| 確率                     | **医療分野で対応する指標**                                      |
+:========================:+:===============================================================:+
| $P(診断結果|感染の有無)$ | **検査後確率**：統計学では**事後確率**と呼ばれる                |
|                          |                                                                 |
|                          | -   **陽性的中率**：陽性と診断されたとき実際に感染              |
|                          | -   **陰性的中率**：陰性と診断されたとき実際に未感染            |
+--------------------------+-----------------------------------------------------------------+
| $P(診断結果|感染の有無)$ | -   **感度**：感染者が陽性と診断される確率↔**偽陰性**に関連     |
|                          | -   **特異度**：未感染者が陰性と診断される確率↔**偽陽性**に関連 |
+--------------------------+-----------------------------------------------------------------+
| $P(感染の有無)$          | **検査前確率**：統計学では**事前確率**と呼ばれる                |
|                          |                                                                 |
|                          | -   検査対象者のなかでの感染者の割合                            |
+--------------------------+-----------------------------------------------------------------+

たとえば，以下のような状況を考えてみましょう．

-   感度・特異度はともに99 %（偽陰性・偽陽性がいずれも1 %の確率で生じる）
-   検査前確率は1 %（感染者は100 人中1 人で残りの99 人は未感染者）

この場合，陽性と診断された場合に感染者である確率$P(感染|陽性)$と，陽性と診断された場合に未感染者である確率$P(未感染|陽性)$は， それぞれ @eq-bayes-covid19-positive となります．

$$
\begin{align}
  P(感染|陽性) \propto P(陽性|感染)P(感染) &= 0.99 \times 0.01 = 0.0099 \\
  P(未感染|陽性) \propto P(陽性|未感染)P(未感染) &= (1 - 0.99) \times (1 - 0.01) = 0.0099
\end{align}
$$ {#eq-bayes-covid19-positive}

@eq-bayes-covid19-positive より，$P(感染|陽性)$と$P(未感染|陽性)$は等しいことがわかり， 陽性的中率は50 %程度となってしまいます．

さらに現実に即した計算事例に興味がある場合は， [統計局の公開しているコラム](https://www.stat.go.jp/library/pdf/cgogai3102.pdf){target="_blank"}もご一読されることをおすすめします．

## 人は直観的にベイズの定理を使っている？

ベイズの定理が示す「検査の精度が高くても陽性的中率が低くなる可能性がある」といった事実は，はじめ多くの人にちょっとした驚きを与えるものかもしれません．そして，こうしたことを踏まえれば，多くの人はベイズの定理をほとんど理解していない，と思われるかもしれません．

しかし，私たちはベイズ更新と呼ばれる手続きを通じて，日頃から無意識に，ベイズの定理を使っている可能性があるのです．以下では，コイントスを題材に，ベイズ更新について説明します．

コイントスの場合には，

-   原因$A$：コインの歪み
-   結果$B$：コイントスの表・裏

と考えることができ， @eq-bayes を @eq-bayes-coin-toss のように置き換えることができます． ここで重要な仮定は，コインの見た目だけでは，コインが歪んでいるかどうか（原因$A$）がわからず， 実際にコイントスをして，その結果を見る必要があるということです． （また，どのコインも必ず表と裏が決まっているものとしましょう）

$$
P(コインの歪み|コイントスの表・裏) \propto P(コイントスの表・裏|コインの歪み) P(コインの歪み)
$$ {#eq-bayes-coin-toss}

### ベイズ更新とは？

ベイズ更新とは，結果（コイントスの表・裏）から原因（コインの歪み）の従う確率分布を

### コイントスの思考実験

あなたは，財布から歪みのないように見えるコインを1枚選んでコイントスをすることにしました．

まず，あなたが，コインを3回投げると，表が1回・裏が2回出ました．

$$
P(B|A) \propto P(A|B) P(B)
$$

```{r}
#| echo: false
#| warning: false

library(tidyverse)

# tibble()
# expand_grid(x = seq(0, 1, 1e-2),
#             )
```
