---
title: "tidymodels&aguaを使って地価を自動機械学習（AutoML）する"
draft: true
---

```{r}
#| label: setup
#| eval: false

library(tidyverse)
library(fs)
library(sf)

library(tidymodels)
library(agua)

h2o_start()

```

```{r}
#| label: download-data
#| eval: false

exdir <- "automl-of-land-prices-using-tidymodels-agua"
dir_create(exdir)

if (!dir_exists(path(exdir, "L01-24_GML"))) {
  zipfile <- file_temp(ext = "zip")
  curl::curl_download("https://nlftp.mlit.go.jp/ksj/gml/data/L01/L01-24/L01-24_GML.zip", zipfile)
  zip::unzip(zipfile = zipfile, 
             exdir = exdir) 
}

file_shape_property <- path(exdir, "shape_property_table2.xlsx")
if (!file_exists(file_shape_property)) {
  curl::curl_download("https://nlftp.mlit.go.jp/ksj/gml/codelist/shape_property_table2.xlsx", file_shape_property)
}

```

```{r}
#| label: load-data
#| eval: false

exdir <- "automl-of-land-prices-using-tidymodels-agua"

file_land_price <- path(exdir, "land_price.gpkg")
if (!file_exists(file_land_price)) {
  file <- dir_ls(exdir,
                 recurse = TRUE,
                 glob = "*.shp")
  
  shape_property <- readxl::read_excel(path(exdir, "shape_property_table2.xlsx"),
                                       sheet = "L01地価公示",
                                       skip = 3) |> 
    select(属性コード, 属性名)
  
  land_price <- sf::read_sf(file) |> 
    rename_with(~ shape_property$属性名,
                shape_property$属性コード)
  
  write_sf(land_price, path(exdir, "land_price.gpkg")) 
}

```

```{r}
#| label: split-data
#| eval: false

exdir <- "automl-of-land-prices-using-tidymodels-agua"

set.seed(1234)

land_price <- read_sf(path(exdir, "land_price.gpkg")) |> 
  select(!ends_with("年公示価格")) |> 
  mutate(st_coordinates(geom) |> 
           as_tibble())

land_price_split <- initial_split(land_price)
land_price_train <- training(land_price_split)
land_price_test <- testing(land_price_split)

model <- auto_ml() |> 
  set_engine("h2o") |>
  set_mode("regression")

recipe <- recipe(地価公示価格 ~ ., 
                 data = st_drop_geometry(land_price_train))

workflow <- workflow() |> 
  add_model(model) |>
  add_recipe(recipe)

fit <- fit(workflow,
           data = st_drop_geometry(land_price_train))
write_rds(fit, path(exdir, "fit.rds"))

```
