---
title: "RでAICの雰囲気をつかむ"
lang: ja
categories: [AIC, R, Japanese]
# date: "2023-09-03"
draft: true
---

```{r}
#| message: false
#| warning: false

library(tidyverse)
```

```{r}
set.seed(1234)

beta <- set_names(rnorm(4), 0:3)

x <- expand_grid(iter = 1:1e2,
                 id = 1:1e2) |> 
  mutate(x1 = rnorm(n()),
         x2 = rnorm(n()),
         x3 = rnorm(n()))

mu <- function(model, x1, x2, x3, beta) {
  case_match(model,
             0 ~ beta["0"],
             1 ~ beta["0"] + beta["1"] * x1,
             2 ~ beta["0"] + beta["1"] * x1 + beta["2"] * x2,
             3 ~ beta["0"] + beta["1"] * x1 + beta["2"] * x2 + beta["3"] * x3) 
}

y <- expand_grid(model = 0:3,
                 x) |> 
  mutate(mu = mu(model, x1, x2, x3, beta)) |> 
  add_column(sigma = 3) |> 
  mutate(y = mu + rnorm(n(), sd = sigma)) |> 
  nest(.by = c(model, iter),
       .key = "data") |> 
  mutate(data = data |> 
           map(\(data) {
             lm_y <- lm(y ~ x1 + x2 + x3, 
                        data = data)
             
             beta_ml <- set_names(coef(lm_y), 0:3)
             sigma_ml <- sqrt(mean(resid(lm_y)^2))
             
             data |> 
               add_column(model = 3,
                          .before = 1) |> 
               mutate(mu_ml = mu(model, x1, x2, x3, beta_ml)) |> 
               select(!model) |> 
               add_column(sigma_ml = sigma_ml)
           })) |> 
  unnest(data)
```

```{r}
y2 <- y |> 
  mutate(loglik_ml = dnorm(y, mu_ml, sigma_ml,
                           log = TRUE)) |>
  rowwise() |> 
  mutate(loglik_true = integrate(\(y) dnorm(y, mu, sigma) *
                                   dnorm(y, mu_ml, sigma_ml,
                                         log = TRUE),
                                 lower = -Inf,
                                 upper = Inf) |> 
           chuck("value")) |> 
  ungroup()
```
